spring:
  application:
    name: barber-manager

  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
        hibernate:
          format_sql: true


jwt:
  secret: "barber-manager-estudo-chave-jwt-32bytes-min"
  expiration-ms: 86400000