spring:
  datasource:
    url: jdbc:postgresql://barber-manager-db.cu7uo8cyy4el.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
